name: ci 
on:
  push: #FIXME should be changed to be at request, manual action run (and should be deployed in default branch to be avaiable)
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: #TODO here to install google-chrome at machine level (apt install ...) - see that you'll need a download (wget) before
      - run: pip install mkdocs-material #TODO replace it with pip install -r requirements.txt
      - run: mkdocs gh-deploy --force #TODO consider replace it with `mkdocs --site-bild docs/`

# -#FIXME: at final take care to have a `gh-deploy` branch in variant `mkdocs gh-deploy --force`
# -#NOTE: as proposed to be modified things shoul happen in `docs/` directory



